### ISSUE TITLE
KPI Target

### ISSUE THREAD

**Issue by yyudim** [billchen198318/bamboobsc#1]
My company breakdown KPI's target into 3 part, treshold (minimum), target and maximum target. Those 3 targets are used to divide employee into 3 criteria. Which employee only able to achieve minimum, which employee able to reach the standard target and which employee able to achieve maximum (or even surpase) target. Can you help us to put these 3 type of targets in your software? Thanking you in advance. 
-YUDI-

**Comment by billchen198318** [comment]
are you means different employees KPI's target value are not same?
example:
if two employee 01-bill  and 02-tiffany,
01-bill and 02-tiffany have KPI named "sales-KPI"
but 01-bill "sales-KPI" target is 100
02-tiffany "sales-KPI" target is 80
it can custom ?

**Comment by yyudim** [comment]
For example:
01-bill has KPI named "sales-KPI" then the target will be like this:
-Minimum  = 80
-Standard  = 100
-Maximum = 120
If 01-bill only achieved 81 then he only achieved a minimum target and need to work harder to achieve the standard target. If his sales is 131 then company will consider a quick promotion for this employee. But if his sales below minimum target (below 80) then this employee will get a warning from the company.

**Comment by billchen198318** [comment]
are you want This information is to be displayed in the KPI-Report or Personal-Report?

**Comment by yyudim** [comment]
Dear Chen,
I attached the example of our manual KPI report. The informations displayed in both KPI-Report & Personal-Report.
![kpi](https://cloud.githubusercontent.com/assets/13596072/9029278/0186dd5a-39bb-11e5-9c24-e7e3bec91540.png)
Thank you

**Comment by billchen198318** [comment]
It may take some time to modify report code, thank

**Comment by yyudim** [comment]
Thank you sir, appreciate a lot..

**Comment by billchen198318** [comment]
Modification completed.

![001](https://cloud.githubusercontent.com/assets/11564867/9033155/63db2ede-39f7-11e5-94e4-95447b308057.png)
![002](https://cloud.githubusercontent.com/assets/11564867/9033157/663faf24-39f7-11e5-84bc-d8dd3f4c7335.png)
![003](https://cloud.githubusercontent.com/assets/11564867/9033160/68ae23d0-39f7-11e5-9458-06ee751a2861.png)
![004](https://cloud.githubusercontent.com/assets/11564867/9033161/6a29a162-39f7-11e5-9f9e-2a5683c07686.png)

But recently, no release plan.
please build run environment on Eclipse-4 by you-self.
Refer to : 
https://github.com/billchen198318/bamboobsc#build-development-environments

and need re-import bbcore.sql ( https://github.com/billchen198318/bamboobsc/blob/master/core-doc/bbcore.sql ) to database.

**Comment by yyudim** [comment]
Thank you, I will try it ..
