### ISSUE TITLE
Real numbers in the measurement

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#10]
In measure, when I put a real number, the number isn't saved. I tried use comma and dot. Integer numbers work.

**Comment by billchen198318** [comment]
view Screenshot
![screenshot-01](https://cloud.githubusercontent.com/assets/11564867/12946498/f21a2e9c-d02f-11e5-84d3-3485a7fd6a03.png)

**Comment by billchen198318** [comment]
A maximum of two decimal places

**Comment by giacomozzi** [comment]
See:

![before](https://cloud.githubusercontent.com/assets/651465/12946887/c4d7eab0-cfde-11e5-8484-b0036c1ee3a4.png)

![after](https://cloud.githubusercontent.com/assets/651465/12946892/cae6978a-cfde-11e5-845b-fc7042d1a453.png)

**Comment by billchen198318** [comment]
it maybe is dojo locale not "en-us" ,  need modify measure input code for non en-us type.

**Comment by billchen198318** [comment]
maybe fix at 0.6.2

**Comment by billchen198318** [comment]
is fix, see comment : https://github.com/billchen198318/bamboobsc/commit/2c4b94974cf7ee6dc60f9a3451b62bc5b910e566
