### ISSUE TITLE
Error load/save Strategy Map

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#11]
Before save:
![before](https://cloud.githubusercontent.com/assets/651465/12947063/0e50fdc0-cfe0-11e5-9170-c34bbdc04e3d.png)

After load:
![after load](https://cloud.githubusercontent.com/assets/651465/12947067/13e397ca-cfe0-11e5-98a4-c6e74f0d898e.png)

Save after load:
![save after load](https://cloud.githubusercontent.com/assets/651465/12947069/19f556e4-cfe0-11e5-8594-ec5683e299b6.png)

**Comment by billchen198318** [comment]
it is fix update ok at 0.6.2 , now 0.6.1 have bug for strategy-map save.

**Comment by billchen198318** [comment]
https://github.com/billchen198318/bamboobsc/commit/63bf572fe58ac22c009c38a0378f94ce73977393
