### ISSUE TITLE
Lines in export strategy map

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#12]
Export strategy map works, but theres no lines!

![strategy-map](https://cloud.githubusercontent.com/assets/651465/12947115/63977322-cfe0-11e5-91fc-d9429d75ebfc.png)

**Comment by billchen198318** [comment]
Unable to export "line" the problem , now yet to find a solution. sorry.

**Comment by billchen198318** [comment]
**Compromise solution:**

1. Click "**Print**" button, the record are read from database history.
![01](https://cloud.githubusercontent.com/assets/11564867/13313742/281c0d6a-dbdb-11e5-809d-cc9e195495fe.png)

2. New open dialog window, wait 2 sec to settings A4 paper **landscape** format.
![02](https://cloud.githubusercontent.com/assets/11564867/13313749/38b40d8a-dbdb-11e5-8a1c-02a26bf8fda9.png)

3. Print result.
![03](https://cloud.githubusercontent.com/assets/11564867/13313761/4b03d5a6-dbdb-11e5-96f0-a906646389b6.jpg)
