### ISSUE TITLE
LDAP login support.

### ISSUE THREAD

**Issue by billchen198318** [billchen198318/bamboobsc#13]
![bamboobsc-login](https://cloud.githubusercontent.com/assets/11564867/13453111/96160aa8-e088-11e5-83e8-530c7897ffa2.png)

Apache shiro configure file location:
**webapps/core-web/WEB-INF/classes/applicationContext/core/**

A. Default login mode.
	copy applicationContext-shiro-default-sample.xml overwrite applicationContext-shiro.xml

B. LDAP login mode.
	copy applicationContext-shiro-ldap-sample.xml overwrite applicationContext-shiro.xml
	and need settings success LDAP server address with DN value.
	
	example:
	
	<bean id="ldapContextFactory" class="org.apache.shiro.realm.ldap.JndiLdapContextFactory">
    	<property name="url" value="ldap://192.168.1.200:389" />       
	</bean>
	
	<bean id="greenStepBaseAuthorizingLdapRealm" class="com.netsteadfast.greenstep.sys.GreenStepBaseAuthorizingLdapRealm">
   		<property name="userRoleService" ref="core.service.UserRoleService"/>
   		<property name="rolePermissionService" ref="core.service.RolePermissionService"/>
   		<property name="cacheManager" ref="shiroCacheManager"/>	
    	<property name="contextFactory" ref="ldapContextFactory" />
    	<property name="userDnTemplate" value="CN={0},OU=people,DC=netsteadfast,DC=com" />
	</bean>

**Comment by rakesh1084** [comment]
Hi,

I used your hint and followed. LDAP Authentication not working. :-(
```
	<bean id="ldapContextFactory" class="org.apache.shiro.realm.ldap.JndiLdapContextFactory">
    	<property name="url" value="ldap://192.168.1.200:389" />       
	</bean>

```	
```
	<bean id="greenStepBaseAuthorizingLdapRealm" class="com.netsteadfast.greenstep.sys.GreenStepBaseAuthorizingLdapRealm">
   		<property name="userRoleService" ref="core.service.UserRoleService"/>
   		<property name="rolePermissionService" ref="core.service.RolePermissionService"/>	
		<property name="cacheManager" ref="shiroCacheManager"/>
    	<property name="contextFactory" ref="ldapContextFactory" />
    	<property name="userDnTemplate" value="CN={MYORG},OU=Users,DC=ALL,DC=COM" />    	
	</bean> 	

```

**Note**:- Other applications like mantisBT is working with the same property.
One thing missing I see in bambooBSC is **username and password**.
I give **username and password** in mantisBT config file and LDAP login work good.
in bambooBSC how and where (which config file ) I give **username and password**.

_**Please guide.**_

**Comment by billchen198318** [comment]
My LDAP environment test is normal, I have no other resources and environment  can to test, sorry
