### ISSUE TITLE
Size of field Target/Actual value

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#16]
I do not know if this is a bug or if I do not know how to use the system.
I have a KPI called 'Cost of acquisition'. The goal is 3,250,100.25. But the Target/Actual value fields support only 3 digits. What can I do? Am I doing right?

**Comment by billchen198318** [comment]
KPI unit enter "million" 
3250100.25 / million = 325
masure data acutal value input 325 or 325.01

**Comment by billchen198318** [comment]
Fix file: 
[fix_measure_data_field.zip](https://github.com/billchen198318/bamboobsc/files/203729/fix_measure_data_field.zip)

1. Download the zip file. unzip it.

2. stop bambooBSC with apache-tomcat, if it running.

3. overwirte gsbsc-standard.jar to gsbsc-web/WEB-INF/lib/gsbsc-standard.jar

4. run SQL command, please view change_measure_data_field.sql. it change bb_measure_data table FLOAT field to DOBULE.
command:
   #> mysql bbcore -u root -p < change_measure_data_field.sql

**Comment by giacomozzi** [comment]
I applied successfully solution 2. Thank you very much!

**Comment by billchen198318** [comment]
not to input value over min: -9999999.00 , max: 9999999.00 , because float value characteristic
