### ISSUE TITLE
Option to inactive a KPI

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#17]
Sometimes, for some reasons, a KPI might be inactive. It would be interesting the possibility to inactivate / activate a KPI.

**Comment by billchen198318** [comment]
Are you mean inactivate the KPI, it not show at Report.
but some-day activate it, will show at Report.

**Comment by giacomozzi** [comment]
Yes!
I it is inactive will not be show in the report.

**Comment by billchen198318** [comment]
Move to issues Plan for 0.6.3: https://github.com/billchen198318/bamboobsc/issues/14
