### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#20]
I think the icons on the menu isn't the saw in the file attached.
![icons](https://cloud.githubusercontent.com/assets/651465/14916109/e782c7a4-0ded-11e6-8f9b-c3c997faf33b.png)
This is a problem?

**Comment by billchen198318** [comment]
not a problem, because dojo 1.11.1 flat themes has special blue block with lose some icon, so need a icon to patch the special block and lose icon, need wait next dojo version fix the flat themes.

**Comment by billchen198318** [comment]
Need clear browser cache, because 0.6.2 page css effective 0.6.3 version.
