### ISSUE TITLE
Feature request - Document meeting

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#21]
Every month we follow the KPI at a meeting.
Everything that is discussed at the meeting is recorded in a document (text).
It would be helpful if the BambooBSC could save this document.
In Brazil we call 'ata'. I did not find the right word in English, but I think it's 'minute'.

Thank you very much!

**Comment by billchen198318** [comment]
KPI then edit model can upload files? the feature not can do?

**Comment by giacomozzi** [comment]
I will discuss with staff ... Thank you!
