### ISSUE TITLE
Question about icons

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#23]
KPI Reports show diferent icons based on KPI value:
![icons](https://cloud.githubusercontent.com/assets/651465/15289972/fa3e5e60-1b4b-11e6-8e0b-7fdd535b4767.png)
The question is: what is the criteria?
With a 83.03 score the exclamation icon is showed;
With a 86.7 score the ok icon is showed.
Can I modify these settings?

**Comment by billchen198318** [comment]
You can custom it, recommended need backup old expression, because expression error will not show report!
![001](https://cloud.githubusercontent.com/assets/11564867/15290664/9b2ca664-1bac-11e6-9dfb-2fe9265f80c9.png)
