### ISSUE TITLE
How to update from 0.6.3 to 0.6.5?

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#26]
How to update from 0.6.3 to 0.6.5?

**Comment by billchen198318** [comment]
Hi 0.6.3 database schema is same 0.6.5 , no need re-import sql file.

**Comment by billchen198318** [comment]
but recommed you need backup old file. In order to avoid a failed upgrade.
thanks, bye.

**Comment by giacomozzi** [comment]
Thank you.
0.6.5 version working here!
