### ISSUE TITLE
Brazilian portuguese translation

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#27]
The translation for brazilian portuguese is incorrete.
I was sended a file with the corret translation in issue number 8, but I think these files are not update.

**Comment by billchen198318** [comment]
you may need send  fix ok *_pt.properties   or *_br.properties language file upload to the issues, i will fix the locale language file update in next version.

**Comment by giacomozzi** [comment]
Here:
[pt-br.zip](https://github.com/billchen198318/bamboobsc/files/407229/pt-br.zip)

**Comment by billchen198318** [comment]
Hi:
"global.properties" file cannot be Brazilian portuguese language use
global.properties is system default for lost locale properties time will use, it need be English
Brazilian portuguese langauge properties  file is **_*_br.properties_**

**Comment by billchen198318** [comment]
Are currently unable to provide the correct language? Or have other problems?
![aaaaaaaaa](https://cloud.githubusercontent.com/assets/11564867/17691856/8df8003c-63c9-11e6-87ef-0159837eb3c4.png)

**Comment by giacomozzi** [comment]
Sorry, my fault. I had not seen the 'BR - Brasil' option.
Even though some parts of the systems are not translated. For example, the menu or some options:

![bamboo1](https://cloud.githubusercontent.com/assets/651465/17734015/1f6a1c86-6450-11e6-9e13-16e83a218ffa.png)

![bamboo2](https://cloud.githubusercontent.com/assets/651465/17734058/4f6e85a2-6450-11e6-8230-05eb8b9bff29.png)

![bamboo3](https://cloud.githubusercontent.com/assets/651465/17734129/a78d1280-6450-11e6-8ece-b207a434cc59.png)

**Comment by billchen198318** [comment]
maybe support the detail locale language config , at next 0.6.7 version.

**Comment by billchen198318** [comment]
**Current Tree-name can modify , use CORE program to do.**

## ***Warning: Please back up your database before modifying***

**A. How to modify system name on Tree-menu**

step 1 - query item
![001](https://cloud.githubusercontent.com/assets/11564867/17735252/ba2b3544-64b3-11e6-8899-4ff84bde03cf.png)


step 2 - modify name and update
![002](https://cloud.githubusercontent.com/assets/11564867/17735260/c9ed8bbc-64b3-11e6-9130-8b14a7c9022c.png)

step 3 - refresh page
![003](https://cloud.githubusercontent.com/assets/11564867/17735313/04f34f44-64b4-11e6-8f58-9a671ce32132.png)




**B. How to modify program name on Tree-menu**

step 1 - query program item
![004](https://cloud.githubusercontent.com/assets/11564867/17735352/47558a5a-64b4-11e6-98f5-989ba94c540f.png)

step 2 - modify program name
![005](https://cloud.githubusercontent.com/assets/11564867/17735372/5dae2f78-64b4-11e6-8cd1-a545a369be39.png)

step 3 - refresh page
![006](https://cloud.githubusercontent.com/assets/11564867/17735381/6ca49b7a-64b4-11e6-862a-2f85bc9662e3.png)

**Comment by billchen198318** [comment]
will support developer Tree-menu multi languages manager function in 0.6.7 version
https://github.com/billchen198318/bamboobsc/issues/28#issuecomment-240899312

**Comment by billchen198318** [comment]
0.6.6 version has support
