### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by 4group** [billchen198318/bamboobsc#28]
Dear Bill Chen
Thank you for very nice and cool project.your projects is very wonderful.
I want to contribute to translate your project to Arabic.
I translate global.properties to Arabic and replace it  but it.
shows unknown characters.whats the problem. What should I do?
Best regards
Hessam

**Comment by billchen198318** [comment]
Hi please use Eclipse to edit the properties file.
or view this 

http://stackoverflow.com/questions/7320573/convert-properties-file-in-arabic-to-unicode

**Comment by billchen198318** [comment]
this is unknown characters settings:
MyLabel = تجربه1

this is success settings:
MyLabel = \u062a\u062c\u0631\u0628\u06471

**Comment by maltourky** [comment]
Hello,

regarding the names from the database tables like tb_sys and tb_sys_prog dos not support multi languages how this should be fixed?

and for a different mater, if we want to use Oracle database what is the approach to do so.?

thank you for your time and good project.

**Comment by billchen198318** [comment]
Hi:
How to modify Tree-menu system-name and program-name please view this issues:
Brazilian portuguese translation : https://github.com/billchen198318/bamboobsc/issues/27#issuecomment-240390218

**Comment by billchen198318** [comment]
Hi , use Oracle database:
current no want to Increase support for other db,  you need self to jump MySQL to Oracle.

Thanks.

**Comment by maltourky** [comment]
Hello Chen,
thanks for your replay 
> How to modify Tree-menu system-name and program-name please view this issues:
Brazilian portuguese translation : #27 (comment)

this makes the change to make the menus for one language and if you want to use form login english and you did translate to arabic the menu will stay in arabic.

**Comment by billchen198318** [comment]
Hi

maybe 0.6.7 will provide tree-menu name for multi languages manager program function. 

but now bambooBSC not found Arabic locale properties  file , so 0.6.7 only support locale:
  br, cn, de, en, es, fr, it, ja, pt, ru, tw. 
not found "ae"
Unless someone provides *_ae.properties file to me

**Comment by maltourky** [comment]
hello, 

> Unless someone provides *_ar.properties file to me

i am working on translation for it and will provide it to you once it finished, you should consider the RTL layout once the arabic language is selected also support n export png files.

**Comment by billchen198318** [comment]
now no enough resources and time to do RTL layout support, If there are enough resources in the future, maybe will plan to support it.

**Comment by maltourky** [comment]
hello Chen,

here in the attached file the *_ar.properties files for arabic support.

[BambooBSC Arabic.zip](https://github.com/billchen198318/bamboobsc/files/491551/BambooBSC.Arabic.zip)

[core-lib_ar.zip](https://github.com/billchen198318/bamboobsc/files/491579/core-lib_ar.zip)


if there is some thing wrong in the translation will updated it. also will provide the menu translation in csv file.

[tb_sys_ar.zip](https://github.com/billchen198318/bamboobsc/files/491586/tb_sys_ar.zip)


[tb_sys_prog_id_name_ar.zip](https://github.com/billchen198318/bamboobsc/files/491575/tb_sys_prog_id_name_ar.zip)


to support the RTL you need to add some dir="RTL" attribute for some body and div elements in all jsp pages and some htm pages as a start then maybe modify some css files to correct some alignments.

**Comment by billchen198318** [comment]
the language locale properties file will add to bamboobsc7 repo. 

thanks.
