### ISSUE TITLE
new feature: support KPIs that are 'referential' in respect to their history

### ISSUE THREAD

**Issue by mahilee** [billchen198318/bamboobsc#3]
For example, a retail store-chain will compare each of its stores customer-sale conversion-rates for each week this year against the same week last year, as a percentage change.
The comparison is made this way because of pedestrian-traffic seasonality e.g. compare golden-week this year vs golden-week last year, and not compare it with the preceding week.

**Comment by billchen198318** [comment]
I will modify, but need take some time.

Then confirm:
and you should refer to this block KPI date range score comparison mode to be corrected?

it can custom compare mode
![screenshot](https://cloud.githubusercontent.com/assets/11564867/10414402/462a4746-7005-11e5-95fe-55b4ff5a0923.png)

**Comment by billchen198318** [comment]
﻿Now adds a new feature "07 - KPI Period Trends"
It calculates the KPI current period score with the KPI previous score trends Change(%).
you can custom KPI's trends formula of "03 - Formula" and "04 - KPI (Edit)"

default trends formula is : 
Change(%) = ( KPI current period score(cv) / KPI previous period score(pv) - 1 ) * 100


![screenshot](https://cloud.githubusercontent.com/assets/11564867/10557599/0c37b9ca-74e6-11e5-8ed0-76728ae1e222.png)

**Comment by billchen198318** [comment]
John is chasing his tail. He is spending a lot of time to this project but but geting nothing.
