### ISSUE TITLE
Login fail.

### ISSUE THREAD

**Issue by maltourky** [billchen198318/bamboobsc#35]
Hello Chen,

i tried to change the source code for the file core-lib.jar and tried to change the line 
```JAVA
public static final String HTML_SELECT_NO_SELECT_NAME=" - please select - ";
```
to 
```JAVA
public static final String HTML_SELECT_NO_SELECT_NAME=" - \u0625\u062E\u062A\u0631 \u0645\u0646 \u0627\u0644\u0642\u0627\u0626\u0645\u0629 - ";
```
or even to 

```JAVA
public static final String HTML_SELECT_NO_SELECT_NAME=" - يرجى الإختيار - ";
```

at the file 
**/core-lib/BASE/com/netsteadfast/greenstep/base/Constants.java**

i also added some files like
**
/core-lib/src/META-INF/resource/grid/ui.grid_ar.properties
/core-lib/src/META-INF/resource/toolbar/ui.toolbar_ar.properties
**
content for  ui.grid_ar.properties :
```JAVA
totalName=\u0627\u0644\u0625\u062C\u0645\u0627\u0644\u064A
pageName=\u0635\u0641\u062D\u0629
rowSizeName=\u062D\u062C\u0645 \u0627\u0644\u0635\u0641
```

content for  ui.toolbar_ar.properties :
```JAVA
createNewName=\u062C\u062F\u064A\u062F
saveName=\u062D\u0641\u0638
exportName=\u062A\u0635\u062F\u064A\u0631
importName=\u0625\u0633\u062A\u064A\u0631\u0627\u062F
refreshName=\u062A\u062D\u062F\u064A\u062B
cancelName=\u0625\u0644\u063A\u0627\u062F
fullscreenName=\u0645\u0644\u0626 \u0627\u0644\u0634\u0627\u0634\u0629 / \u062E\u0631\u0648\u062C \u0645\u0646 \u0645\u0644\u0626 \u0627\u0644\u0634\u0627\u0634\u0629
```
 and when i exported the file as jar file and replaced it with the corresponding one in each webapp i got login fail message and i don't know what i have made wrong ?

and here in the attached files you can find the generated jar file:
[core-lib.jar.zip](https://github.com/billchen198318/bamboobsc/files/487361/core-lib.jar.zip)

also i forget to mention that  when exporting to jar i got error for the manifest for the first time, but the second time i used the one
***
/core-web/WebContent/META-INF/MANIFEST.MF
***
i don't know if this is wrong? :) as i told you i am not in JAVA development at all.

**Comment by billchen198318** [comment]
This is success
```JAVA
public static final String HTML_SELECT_NO_SELECT_NAME=" - \u0625\u062E\u062A\u0631 \u0645\u0646 \u0627\u0644\u0642\u0627\u0626\u0645\u0629 - ";
```

add *_ar.properties need config with lang.json add "ar" item

login fail , please confirm the database connection settings file has config

are you use Eclipse to work?

**Comment by billchen198318** [comment]
Are you has do convert database jump to Oracle-DB now?

**Comment by billchen198318** [comment]
Because bambooBSC 0.7.0 version will support Oracle-DB, now I do not recommend you use too much time to modified version 0.6.6 code.
And because of the 0.7.0 version will be of more change

**Comment by maltourky** [comment]
>add *_ar.properties need config with lang.json add "ar" item

yes i did add arabic to the file lang.json
```JAVA
"langs"		: {
		"ar"		:	"AR - Arabic",
```

>login fail , please confirm the database connection settings file has config

it is configured correctly as it was working fine before changing the core-lib.jar, but thanks it is working now i think, only the issue now is after login it give me a message 
```please login again.!```
i think i did not export the jar file correctly. but if i ignored the message the system still working no need to re-login unless i refresh the page.
 
>are you use Eclipse to work?

yes i am , as i follow the steps you describe here [https://github.com/billchen198318/bamboobsc#build-development-environments](url)

before i was working with netbeans for PHP development.

>Are you has do convert database jump to Oracle-DB now?

not really but i used program called DBSync to sync between the two databases, 
 [https://dbconvert.com/mysql/oracle/](url) 
and it is still really hard as the database you created and as you inform me that it has reserved word in the table names and also the indexes and triggers - some triggers did not create in the Oracle DB- has long names. i did change the names for the tables form _**sys**_ to _**bsc**_ and still facing problems.
here is some errors the application DBSync provided:
```
Creating table 'tb_bsc_mail_helper'.
-- Error 1408: ORA-01408: such column list already indexed
Creating table 'tb_bsc_menu_role'.
-- Error 2264: ORA-02264: name already used by an existing constraint
Copying data for table 'bb_formula'.
-- Error 12899: ORA-12899: value too large for column "BBCORE"."bb_formula"."NAME" (actual: 102, maximum: 100)
Copying data for table 'bb_kpi'.
-- Error 12899: ORA-12899: value too large for column "BBCORE"."bb_kpi"."NAME" (actual: 125, maximum: 100)

-- Error 12899: ORA-12899: value too large for column "BBCORE"."kpi_bb_kpi"."NAME" (actual: 105, maximum: 100)
```
>Because bambooBSC 0.7.0 version will support Oracle-DB, now I do not recommend you use too much time to modified version 0.6.6 code.
And because of the 0.7.0 version will be of more change

i am waiting actually for you to provide the new version - Thank you for that :) - but  the expected time is missing here. otherwise i had to start studying JAVA development and do it myself, and the expected time for that is 6-12 months minimum :))
