### ISSUE TITLE
Employee Hierarchy Setting

### ISSUE THREAD

**Issue by mohandasp** [billchen198318/bamboobsc#38]
Can we set employee manager relation in this application?

**Comment by billchen198318** [comment]
Is the relationship similar to a tree? now is no support.

**Comment by mohandasp** [comment]
yes, all reports link employee to department/organisation but not to his manager. It would be good to see an employee linked to both his manager and organisation.

**Comment by billchen198318** [comment]
This idea is good, later versions maybe will support.
maybe 0.7.1 will do it.

**Comment by billchen198318** [comment]
Issues move to https://github.com/billchen198318/bamboobsc/issues/39
