### ISSUE TITLE
Version 0.7.1 ( will release at 2017/03/01 )

### ISSUE THREAD

**Issue by billchen198318** [billchen198318/bamboobsc#39]
**_1. Employee Hierarchy Setting. https://github.com/billchen198318/bamboobsc/issues/38#issuecomment-271556171_**

**_2. Streamlined the KPI aggregate method expression content, The current expression content is too complex not easy to modify._**

**_3. Time Series Analysis, ARIMA_**

<br>
<br>

Error / Bug :
Mobile version modal show work error with bootstrap V4 aplha6.
not good modify ( https://github.com/billchen198318/bamboobsc/commit/b7747597bce5eab889a007db702b56ea751da744 ), but can work with mobile version.

<br>
<br>

SQL script update:

New table:
bb_employee_hier
bb_tsa
bb_tsa_measure_freq
bb_tsa_ma_coefficients

<br>
<br>

Content update:
tb_sys_ctx_bean
bb_aggregation_method
tb_sys_prog
tb_role_permission

<br>
<br>
<br>
<br>

**Employee Hierarchy Setting**

1. Use "01 - Employee" to setting
![006](https://cloud.githubusercontent.com/assets/11564867/22188513/d92469f6-e150-11e6-881c-c9ae4668916e.png)

2. Drag item to hierarchy 
![007](https://cloud.githubusercontent.com/assets/11564867/22188525/023c8b52-e151-11e6-95a3-941f2fbd56c3.png)

( Organization/Department hierarchy  settings, please use "02-Organization" to config on organzation tree )

**BSC report click employee name or organization/department label to show hierarchy view** 
![001](https://cloud.githubusercontent.com/assets/11564867/22188535/2ff59e62-e151-11e6-86a8-c612622458cf.png)

<br>

![004](https://cloud.githubusercontent.com/assets/11564867/22188537/39132afa-e151-11e6-921a-f86177f7067c.png)

<br>

![005](https://cloud.githubusercontent.com/assets/11564867/22188541/42d135fa-e151-11e6-9932-6959cdec3839.png)

<br>

**Employee hierarchy  view**
![002](https://cloud.githubusercontent.com/assets/11564867/22188551/4fceccd6-e151-11e6-9c98-88cf23191be0.png)

<br>

**Organization/Department hierarchy  view**
![003](https://cloud.githubusercontent.com/assets/11564867/22188554/596afc42-e151-11e6-80c8-90876588983d.png)

<br>
<br>

**Time Series Analysis**

1. Create param item.
![001](https://cloud.githubusercontent.com/assets/11564867/22868387/5a5e5308-f1d0-11e6-9aff-a6f204cb8791.png)

<br>

2. Query forecast analysis
![002](https://cloud.githubusercontent.com/assets/11564867/22868337/dc970956-f1cf-11e6-91a7-fbf384fe1971.png)

<br>

![003](https://cloud.githubusercontent.com/assets/11564867/22868339/e1840ffe-f1cf-11e6-87d4-ea17842daae1.png)

<br>
<br>

**Comment by asherif-as** [comment]
how to add this script

**Comment by billchen198318** [comment]
Hi asherif-as:

The will release at 0.7.1 version, now version 0.7.0 no support.

**Comment by asherif-as** [comment]
i'am waiting for new release 0.7.1 to add Employee Hierarchy Setting
