### ISSUE TITLE
bbcore.sql

### ISSUE THREAD

**Issue by tonylom3** [billchen198318/bamboobsc#40]
Hello, when trying to run "bbcore.sql" I get the following error.

bsc@1018:~/bamboobsc-0.7.0-RELEASE$ mysql bbcore -u root -p < bbcore.sql
Enter password: 

ERROR 1064 (42000) at line 25: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `USE' at line 8

From what I gather from searching, this has something to do with the syntax for "timestamp". But I haven't been able to figure out what that is exactly. I am running MySQL version 5.5.54.

Thank you!
Tony

**Comment by billchen198318** [comment]
Hi

Please upgrade mysql to 5.6 version
The SQL dump file cannot import to mysql 5.5

Thanks
