### ISSUE TITLE
how to manage user permission 

### ISSUE THREAD

**Issue by asherif-as** [billchen198318/bamboobsc#41]
i need to give all users permission to access his KPI's

**Comment by billchen198318** [comment]
https://github.com/billchen198318/bamboobsc/blob/master/core-doc/dev-docs/06-RoleAndAuthoritySettings.md

**Comment by billchen198318** [comment]
default user role is `BSC_STANDARD` , this role can access KPI function.

**Comment by Gustavo20Usac** [comment]
can i set KPI only for a group of users access?
