### ISSUE TITLE
KIP update 

### ISSUE THREAD

**Issue by Gustavo20Usac** [billchen198318/bamboobsc#43]
i have an issue when i'm trying to update KPI information

![image](https://cloud.githubusercontent.com/assets/3586174/24020218/cf01938e-0a60-11e7-9d3e-97c2e2a77b0c.png)

**Comment by billchen198318** [comment]
i try work OK.
please check your computer environment is OK, etc memory(RAM)  Is it enough? https://github.com/billchen198318/bamboobsc/issues/42
 or database connection is OK??? has import success database (bbcore.sql) data ...

![f0001](https://cloud.githubusercontent.com/assets/11564867/24024458/8988751e-0aee-11e7-9cbc-420cf1f50678.png)

**Comment by billchen198318** [comment]
Java incompatible magic value https://techhelpkb.com/java-incompatible-magic-value/
