### ISSUE TITLE
Strategy map issue

### ISSUE THREAD

**Issue by Gustavo20Usac** [billchen198318/bamboobsc#44]
when i try to see the strategy map, i have this error.

	javax.servlet.ServletException: java.lang.ClassFormatError: Incompatible magic value 0 in class file org/apache/jsp/pages/strategy_002dmap/strategy_002dmap_002dmanagement_jsp	class javax.servlet.ServletException
exceptionStack	javax.servlet.ServletException: java.lang.ClassFormatError: Incompatible magic value 0 in class file org/apache/jsp/pages/strategy_002dmap/strategy_002dmap_002dmanagement_jsp at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:349) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466) at 

![image](https://cloud.githubusercontent.com/assets/3586174/24020331/47d96a20-0a61-11e7-8209-475e80e1a5fd.png)

**Comment by billchen198318** [comment]
i try work OK.
please check your computer environment is OK, etc memory(RAM) Is it enough? https://github.com/billchen198318/bamboobsc/issues/42
or database connection is OK??? has import success database (bbcore.sql) data ...
![f0002](https://cloud.githubusercontent.com/assets/11564867/24024479/c5034f42-0aee-11e7-8143-f8ce9b131987.png)

**Comment by billchen198318** [comment]
Java incompatible magic value https://techhelpkb.com/java-incompatible-magic-value/

**Comment by Gustavo20Usac** [comment]
i am trying with the VM edition, i have set 2 gb of Ram. its enought?

**Comment by billchen198318** [comment]
need set start shell command file , please view https://github.com/billchen198318/bamboobsc/issues/42
recommed change use manual install version
