### ISSUE TITLE
Bug for export SVG chart

### ISSUE THREAD

**Issue by billchen198318** [billchen198318/bamboobsc#49]
Bug for export SVG chart.
InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range

BUG FIX OK: https://github.com/billchen198318/bamboobsc/commit/17f50a74f779ce2e9098c81d541899b801036625

**Comment by quangnguyen9x** [comment]
Hi, i tryed to fix with new commit, but not work. Please help me. Thanks so much.

**Comment by billchen198318** [comment]
Are you use 0.7.2p1 version?

**Comment by billchen198318** [comment]
I try 0.7.2p1 version, export SVG chart is work success.

**Comment by quangnguyen9x** [comment]
I use 0.7.1, but i fixed your file you commit. And i don't export excel, pdf.

**Comment by billchen198318** [comment]
I recommend you change use 0.7.2p1 , old version   0.7.1 or 0.7.1p1 upgrade to 0.7.2p1 no need re-import database , but recommend need backup .
If you self modify code, but cannot run , I no way to support it.

**Comment by quangnguyen9x** [comment]
Thank you. I have fixed to export excel.
