### ISSUE TITLE
About initiatives

### ISSUE THREAD

**Issue by Chibipond** [billchen198318/bamboobsc#56]
Hi Billchen,

First of all, thank you for contributing such an amazing strategy tool.

However, I can't find the initiative section. Do you have one hidden somewhere in the tool?
Or is there anyway to add more field into this tool?

Thank you in advance.
Pond

**Comment by billchen198318** [comment]
Hi.

Your description is too general. Can you describe it in more detail? 
Do you need some features, but bambooBSC do not have it? or can not find it.
Or do you want to add some features?

Thanks.

**Comment by oavd26** [comment]
hello Bildchen,

We are implementing an excellent application, but I have the same doubt about this user in said application there is no module where the organization's initiatives can be placed.

Those initiatives are the ideas that are carried out to initiate or undertake the continuous improvement of the organization.

example: develop and conduct CCTV project by stage for an organization

formulation and budget control.

These activities are taken as strategic initiatives for continuous improvement of the processes or of the organization itself, it can be said that it has an expiration date, it also has a person in charge, in the same way it can be a specific department, such as the whole organization more or less as the PDCA is something like that.

greeting
