### ISSUE TITLE
KPI management method 

### ISSUE THREAD

**Issue by abdelazizelesh** [billchen198318/bamboobsc#63]
I tried to get a difference between kpi management (smaller is better & bigger is better) in kpi report, but I found both are same.

**Comment by billchen198318** [comment]
Hi

It, usually is just for display, But you want difference effective score for dashboard, maybe need custom add Formula( `03 - Formula` ) by you self, custom new formula for the `bigger is better` or `smaller is better`.

Need Custom KPI-report icon please view issues: https://github.com/billchen198318/bamboobsc/issues/23
Need Custom KPI-report COLOR please view issues: https://github.com/billchen198318/bamboobsc/issues/29


bye.
