### ISSUE TITLE
System requiremnts

### ISSUE THREAD

**Issue by abdelazizelesh** [billchen198318/bamboobsc#68]
What is the minimum requirements to install system in linux environment?
RAM
CPUs
DISK space

Thanks

**Comment by billchen198318** [comment]
RAM: 
2G Free-space, you can adjustable tomcat8 `catalina.sh` args `Xmx` , bambooBSC release package settings is 1280 MB.

CPU: 
Core 2 duo or better

DISK space: 
manual install version after decompression need 2G space, 
VM version after decompression need 5G space.
