### ISSUE TITLE
Tasks if KPI is not reached

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#7]
When a KPI is not reached it should be possible to create one or more tasks, with starting and end date, cost and responsible, with activities to bring the KPI index back to goal.

**Comment by billchen198318** [comment]
This issues request will be into when the "0.6.3" development plan, so need wait some time.

**Comment by billchen198318** [comment]
Please provide a detailed description of the process, help to understand development needs.

**Comment by billchen198318** [comment]
issues merge to Plan for 0.6.3

**Comment by giacomozzi** [comment]
Sorry for the delay.
The idea is use PDCA: https://en.wikipedia.org/wiki/PDCA
Here in my organization, when a target is not reached, we create a FCA - Fact, cause, action. I mean, if a target is no reached, we registrer what, why and how we can correct this.
My sugestion is when a target is not reached can create a FCA.
The FCA must contain:
Fact - description of the fact
Cause - root cause analysis
Action - the action taken to resolve the problem
It is necessary a person resposable, dates to start and finishe and cost.

**Comment by billchen198318** [comment]
This part will be the reference PDCA/FCA, adding the plan 0.6.3
issues move to : https://github.com/billchen198318/bamboobsc/issues/14
