### ISSUE TITLE
How can I use Weight value in Formula to create New formula?

### ISSUE THREAD

**Issue by ramu02** [billchen198318/bamboobsc#71]

**Comment by billchen198318** [comment]
Current Formula cannot get KPI WEIGHT need modify code, but aggregation-method can use KPI WEIGHT.

**Comment by ramu02** [comment]
Hi,

Formula: (Actual /Target) * Weight 

I want to configure the above formula. In your update you said that it will be provided in 0.7.5. How can we configure using aggregation method. Please assist

**Comment by billchen198318** [comment]
![2018-12-04 16-51-34](https://user-images.githubusercontent.com/11564867/49430252-7bb79380-f7e5-11e8-84b6-ccd66f0920c6.png)

**Comment by ramu02** [comment]
Thank you for update.
