### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#8]
How can I make the translation into Portuguese of Brazil?

**Comment by billchen198318** [comment]
This part is currently no plan Portuguese of Brazil.

**Comment by billchen198318** [comment]
if have enough time, maybe provide support it ( Brazil language ) at "0.6.3" version.

**Comment by giacomozzi** [comment]
I can do this. How I can help?

**Comment by billchen198318** [comment]
please reference Struts 2 internationalizing(i18n), localization(i10n) or multi-lingua example :
http://www.mkyong.com/struts2/struts-2-i18n-or-localization-example/

CORE-WEB locale properties files:
https://github.com/billchen198318/bamboobsc/blob/master/core-web/resource/global.properties
https://github.com/billchen198318/bamboobsc/tree/master/core-web/resource/com/netsteadfast/greenstep/action

GSBSC-WEB locale properties files:
https://github.com/billchen198318/bamboobsc/blob/master/gsbsc-web/resource/global.properties
https://github.com/billchen198318/bamboobsc/tree/master/gsbsc-web/resource/com/netsteadfast/greenstep/bsc/action

QCHARTS-WEB locale properties files:
https://github.com/billchen198318/bamboobsc/blob/master/qcharts-web/resource/global.properties
https://github.com/billchen198318/bamboobsc/tree/master/qcharts-web/resource/com/netsteadfast/greenstep/qcharts/action

locale select item config:
https://github.com/billchen198318/bamboobsc/blob/master/core-base/src/META-INF/lang.json

Build development environments:
https://github.com/billchen198318/bamboobsc#build-development-environments

**Comment by luigicolombelli** [comment]
I can help with the translation.

**Comment by billchen198318** [comment]
Ok, thanks.

**Comment by billchen198318** [comment]
So long no news, do it by myself.

**Comment by giacomozzi** [comment]
The translation in the 0.6.3 version is incorret.
Can I copy the files, translate and send back to you?

**Comment by billchen198318** [comment]
ok you can send fix locale file to me, i use Google-translate maybe have some is incorrect.

**Comment by giacomozzi** [comment]
Brazilian Portuguese files attached.
[pt-br.zip](https://github.com/billchen198318/bamboobsc/files/242940/pt-br.zip)
