### ISSUE TITLE
HTTP Status 500 – Internal Server Error

### ISSUE THREAD

**Issue by fahemadeveloper** [billchen198318/bamboobsc#80]
![image](https://user-images.githubusercontent.com/45529471/50220589-cae3f380-03a3-11e9-917d-841011b79871.png)

I am getting this error. i have configured it on my Windows Server 2008 R2. i have done manual Installation..
when i tired to run the application its giving me this error. Please Help

**Comment by billchen198318** [comment]
trace log C:\tmp\greenstep-core.log and C:\tmp\greenstep-gsbsc.log
