### ISSUE TITLE
KPI target

### ISSUE THREAD

**Issue by giacomozzi** [billchen198318/bamboobsc#9]
Why KPI target cannot be 0 (zero)?
For example, I have a employee death target that must be 0.

**Comment by billchen198318** [comment]
KPI target is zero, this request not consistent with the many of users. 
I recommend modify it by yourself.
please modify check target/weight expression for KPI create/save.

1. query check target/Max expression for KPI save/update.
![screenshot-01](https://cloud.githubusercontent.com/assets/11564867/12936983/ccc6f95a-cfde-11e5-8508-b67214b36258.png)

2. modify and update expression content.
![screenshot-02](https://cloud.githubusercontent.com/assets/11564867/12936985/cf740bd4-cfde-11e5-9320-d710788dca64.png)
