### ISSUE TITLE
Setting Up the Developer Environment for BambooBSC - 0.7.8

### ISSUE THREAD

**Issue by Junaid-Amjad** [billchen198318/bamboobsc#95]
hi @billchen198318 hope you are fine and in good health. I am trying to setup the development environment for bamboobsc 0.7.8 but faced error after completing all the process [from this link](https://github.com/billchen198318/bamboobsc#1-download-archives-file). 
![1](https://user-images.githubusercontent.com/75033105/102098537-2dfca980-3e49-11eb-96e5-fbeba8605d84.png)
![2](https://user-images.githubusercontent.com/75033105/102098541-2f2dd680-3e49-11eb-9304-64eb394546e5.png).

I am using below software for my environment
1. Windows 10
2. Eclipse Oxygen
3. JDK 8
4. Tomcat 8.5

The only solution which i found for these errors was to clean to project which i did but errors were not resolved. Please help me sorting out this issue. Thanks in advance

**Comment by billchen198318** [comment]
Reference the step-by-step build development environment video.
download from https://github.com/billchen198318/bamboobsc/releases/download/v0.7.8/bamboobsc-0.7.8-build-dev-env-mp4-video.7z
need use 7zip to extract.

**Comment by Junaid-Amjad** [comment]
@billchen198318 Thanks for the video, but i configured it after google the problems. It is configured and running on the browser right now. The steps you have taken is different then the steps which i take from the google. If i face any issue related to the application then i will cross verify it from the video. Thanks for the help.

**Comment by Junaid-Amjad** [comment]
Hi @billchen198318, i want to host the application on public URL. Can you explain how can i host it on IIS or others?
